version: '3.8'

volumes:
  backend_node_modules:
  mongo_volume:


services:
  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - "3500:3500"
    environment:
      - "NODE_ENV=dev"
      - "PORT=3500"
    volumes:
      - ./server/:/opt/app
      - backend_node_modules/:/opt/app/node_modules
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_volume:/data/db
